version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    restart: always
    command: pnpm dev
    image: chirp
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    env_file:
      - .env
